// (C) 2026 Rodrigo Rodrigues da Silva <rodrigo@flowlexi.com>
// SPDX-License-Identifier: Apache-2.0
//
// gen-docs.mjs — emit docs/reference/api.md from src/index.ts. Regex on
// our own conventional source, not a TS parser: every public method is
// `name(` at two-space indent, preceded by an optional JSDoc line, and
// hits exactly one `this.request("METHOD", \`path\`)` call.
// ponytail: swap for typedoc when the surface outgrows one class.
import { readFileSync } from "node:fs";

const src = readFileSync(new URL("../src/index.ts", import.meta.url), "utf8");
const version = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
).version;

const methods = [];
const re =
  /(?:\/\*\*\s*([^*]*?)\s*\*\/\s*)?^  (?:async )?(\w+)\(([\s\S]*?)\)(?::[^{]+)?\{([\s\S]*?)^  \}/gm;
for (const m of src.matchAll(re)) {
  const [, doc, name, params, body] = m;
  if (name === "constructor" || name.startsWith("raw")) continue;
  const call = body.match(/"(GET|POST|PUT|DELETE|PATCH)",\s*[`"]([^`"]+)[`"]/);
  if (!call) continue;
  methods.push({
    name,
    params: params.replace(/\s+/g, " ").trim(),
    doc: (doc ?? "").replace(/\s+/g, " ").trim(),
    method: call[1],
    path: call[2].replace(/\$\{enc\((\w+)\)\}/g, "{$1}").replace(/\$\{(\w+)\}/g, "{$1}"),
  });
}

if (methods.length === 0) {
  console.error("gen-docs: no methods extracted — source drifted?");
  process.exit(1);
}

const lines = [
  "<!-- Generated by scripts/gen-docs.mjs — do not edit by hand. -->",
  "",
  `# PaveDB TypeScript Client — API reference (v${version})`,
  "",
  "Construct with `new PaveDBClient({ baseUrl, apiKey })`;",
  "`fetchImpl` and `timeoutMs` are optional. Errors throw `PaveDBError`",
  "with `status`, `code`, and the server message.",
  "",
  "| Method | HTTP route |",
  "|---|---|",
  ...methods.map(
    (m) => `| \`${m.name}(${m.params})\` | \`${m.method} ${m.path}\` |`,
  ),
  "",
  "## Notes",
  "",
  ...methods
    .filter((m) => m.doc)
    .map((m) => `- \`${m.name}\` — ${m.doc}`),
  "",
];
process.stdout.write(lines.join("\n"));
